/**
 * Cloudflare Worker for wetheagents.ai
 *
 * Serves the entire site from the docs/ static assets. /btc is a static
 * daily snapshot of btc_dashboard, regenerated by .github/workflows/btc-snapshot.yml
 * and served as a regular directory under docs/btc/.
 */
export default {
  async fetch(request, env) {
    return env.ASSETS.fetch(request);
  },
};
