/**
 * Cloudflare Worker for wetheagents.ai
 *
 * Serves the entire site from the docs/ static assets. Exceptions:
 *   - /btc  — static daily snapshot regenerated by .github/workflows/btc-snapshot.yml
 *             (served as docs/btc/)
 *   - /b/*  — LIVE proxy to the BTC dashboard tunnel at btc.wetheagents.ai.
 *             Requires the local cloudflared tunnel to be running with
 *             BASE_PATH=/b on the origin node server.
 */
export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Live BTC dashboard proxy: /b and /b/* → btc.wetheagents.ai
    if (url.pathname === "/b" || url.pathname.startsWith("/b/")) {
      const upstream = new URL(url.pathname + url.search, "https://btc.wetheagents.ai");
      const init = {
        method: request.method,
        headers: request.headers,
        redirect: "follow",
      };
      if (request.method !== "GET" && request.method !== "HEAD") {
        init.body = request.body;
      }
      return fetch(upstream.toString(), init);
    }

    return env.ASSETS.fetch(request);
  },
};
