#!/bin/bash
# Cloud Agent Setup — runs at session start, before Claude Code launches.
# Prepares worktrees, CLI tools, and agent identities for cloud-based agents.
#
# Usage:
#   cloud_agent_setup.sh              — full setup (steps 1-7, deploys genomes)
#   cloud_agent_setup.sh --retrieve   — retrieve genomes from all worktrees
#   cloud_agent_setup.sh --retrieve --agent cursor-3  — retrieve one agent
#
# Required env vars (set in cloud session settings):
#   CLAUDE1_GITHUB_TOKEN  — fine-grained PAT for Claude-1 GitHub account
#   CODEX2_GITHUB_TOKEN   — fine-grained PAT for Codex-2 GitHub account
#
# Optional:
#   OPENAI_API_KEY        — for codex CLI (if using API mode)
#   WEA_AUTH_PROXY_TOKEN  — generated by auth_proxy.py and exported by setup
#
# PAT permissions (fine-grained, repo: WeTheAgents/wetheagents):
#   Contents:     Read and write
#   Issues:       Read and write
#   Pull requests: Read and write
#   Metadata:     Read-only (auto-included)

set -euo pipefail

REPO=/home/user/wetheagents
SESSION_ID="a0-$(hostname -s 2>/dev/null || echo local)-$(date +%s)"
ACQUIRED_AGENTS=()
AGENT_LOCK="$REPO/scripts/agent_lock.py"

# NOTE: No trap EXIT for lock cleanup here.
# Locks persist beyond setup — they protect agents during their entire runtime.
# Locks auto-expire via TTL (default 2h). To release manually:
#   python3 scripts/agent_lock.py release-all --session "$SESSION_ID"

# ── Agent registry ──────────────────────────────────────────
# Format: "slug|genome_id|agent_type|branch|display_name|email"
# agent_type: cli = AGENTS.local.md, ide = AGENTS.md (with YAML frontmatter)
AGENTS=(
  "claude-1|Claude-1@claude|cli|agent/Claude-1/work|Claude-1|claude-1@claude"
  "codex-2|Codex-2@codex|cli|agent/Codex-2/work|Codex-2|codex-2@codex"
  "cursor-3|Cursor-1@cursor|ide|agent/Cursor-3/work|Cursor-3|cursor-3@cursor"
  "gemini-4|gemini-4@google|cli|agent/gemini-4/work|gemini-4|gemini-4@google"
  "claude-5|Claude-5@claude|cli|agent/Claude-5/work|Claude-5|claude-5@claude"
  "claude-6|Claude-6@claude|cli|agent/Claude-6/work|Claude-6|claude-6@claude"
)

YAML_FRONTMATTER="---
description:
alwaysApply: true
---"

# ── Parse arguments ─────────────────────────────────────────
MODE="setup"
FILTER_AGENT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --retrieve)  MODE="retrieve"; shift ;;
    --agent)     FILTER_AGENT="$2"; shift 2 ;;
    *)           echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Helper functions ────────────────────────────────────────

create_worktree() {
  local agent_slug="$1" branch_name="$2"
  local wt="/home/user/wetheagents-${agent_slug}"
  if [ -d "$wt" ]; then
    echo "  worktree ${agent_slug} already exists, syncing..."
    git -C "$wt" merge origin/main --no-edit 2>/dev/null || true
    return
  fi
  # Check if branch exists locally or on remote
  if git show-ref --verify --quiet "refs/heads/${branch_name}" 2>/dev/null; then
    git worktree add "$wt" "$branch_name"
  else
    git worktree add "$wt" -b "$branch_name" origin/main 2>/dev/null \
      || git worktree add "$wt" -b "$branch_name" HEAD
  fi
}

resolve_agent_domain() {
  # Resolve domain for an agent from ledger/domains.json
  # Usage: resolve_agent_domain <genome_id>
  # Prints domain name (or "core" if unassigned)
  local genome_id="$1"
  local domains_file="$REPO/ledger/domains.json"
  if [ ! -f "$domains_file" ]; then
    echo "core"; return
  fi
  local domain
  domain=$(python3 -c "
import json, sys
data = json.load(open(sys.argv[1]))
a = data.get('assignments', {}).get(sys.argv[2], {})
print(a.get('domain', 'core'))
" "$domains_file" "$genome_id" 2>/dev/null) || domain="core"
  echo "$domain"
}

deploy_genome() {
  local slug="$1" genome_id="$2" agent_type="$3"
  local wt="/home/user/wetheagents-${slug}"

  # Check for domain-specific genome
  local domain
  domain=$(resolve_agent_domain "$genome_id")
  local domain_genome="$REPO/genomes/${genome_id}/domains/${domain}.md"
  local base_genome="$REPO/genomes/${genome_id}/AGENTS.local.md"

  local genome_src
  if [ "$domain" != "core" ] && [ -f "$domain_genome" ]; then
    genome_src="$domain_genome"
    echo "  ${slug}: using domain genome (${domain})"
  else
    genome_src="$base_genome"
  fi

  if [ ! -f "$genome_src" ]; then
    echo "  WARN: genome not found: $genome_src"; return 0
  fi

  if [ "$agent_type" = "cli" ]; then
    cp "$genome_src" "${wt}/AGENTS.local.md"
    echo "  ${slug}: AGENTS.local.md (cli)"
  else
    # IDE agents read AGENTS.md, not AGENTS.local.md
    { printf '%s\n\n' "$YAML_FRONTMATTER"; cat "$genome_src"; } > "${wt}/AGENTS.md"
    # Hide from git status — AGENTS.md is tracked, prevent accidental commits
    git -C "$wt" update-index --assume-unchanged AGENTS.md 2>/dev/null || true
    echo "  ${slug}: AGENTS.md (ide, frontmatter added)"
  fi
}

retrieve_genome() {
  local slug="$1" genome_id="$2" agent_type="$3"
  local genome_dst="$REPO/genomes/${genome_id}/AGENTS.local.md"
  local wt="/home/user/wetheagents-${slug}"

  if [ "$agent_type" = "cli" ]; then
    local src="${wt}/AGENTS.local.md"
    if [ ! -f "$src" ]; then
      echo "  WARN: ${src} not found, skipping"; return 0
    fi
    cp "$src" "$genome_dst"
  else
    local src="${wt}/AGENTS.md"
    if [ ! -f "$src" ]; then
      echo "  WARN: ${src} not found, skipping"; return 0
    fi
    # Strip YAML frontmatter (--- ... ---) and blank line after it
    # Only activates if line 1 is exactly "---"; safe if no frontmatter
    awk '
      NR==1 && /^---$/ { in_fm=1; next }
      in_fm && !fm_done && /^---$/ { fm_done=1; next }
      fm_done && !blanked && /^$/ { blanked=1; next }
      !in_fm || fm_done { print }
    ' "$src" > "$genome_dst"
  fi
  echo "  ${slug}: genome retrieved -> genomes/${genome_id}/"
}

# ── Retrieve mode (early exit) ──────────────────────────────
if [ "$MODE" = "retrieve" ]; then
  echo "=== Genome Retrieve ==="
  for entry in "${AGENTS[@]}"; do
    IFS='|' read -r slug genome_id agent_type _branch _name _email <<< "$entry"
    [ -n "$FILTER_AGENT" ] && [ "$slug" != "$FILTER_AGENT" ] && continue
    retrieve_genome "$slug" "$genome_id" "$agent_type"
  done
  echo "=== Done ==="
  exit 0
fi

# ── Normal setup flow ───────────────────────────────────────
echo "=== Cloud Agent Setup ==="

# ── 1. Install gh CLI ──────────────────────────────────────────────
if ! command -v gh &>/dev/null; then
  echo "[1/8] Installing gh CLI..."
  curl -sL "https://github.com/cli/cli/releases/download/v2.87.3/gh_2.87.3_linux_amd64.tar.gz" \
    | tar -xz -C /tmp
  cp /tmp/gh_2.87.3_linux_amd64/bin/gh /usr/local/bin/gh
else
  echo "[1/8] gh CLI already installed"
fi

# ── 2. Install wea CLI in .venv ────────────────────────────────────
echo "[2/8] Installing wea CLI..."
cd "$REPO"
if [ ! -d .venv ]; then
  python3 -m venv .venv
fi
. .venv/bin/activate
pip install -q -e .

# ── 3. Fetch latest main ──────────────────────────────────────────
echo "[3/8] Fetching latest main..."
git fetch origin main 2>/dev/null || true

# ── 4. Acquire locks + create worktrees ──────────────────────────
echo "[4/8] Acquiring locks and creating worktrees... (session: $SESSION_ID)"
for entry in "${AGENTS[@]}"; do
  IFS='|' read -r slug _gid _type branch _name _email <<< "$entry"
  lock_stderr=$(mktemp)
  if python3 "$AGENT_LOCK" acquire "$slug" --session "$SESSION_ID" --ttl 7200 2>"$lock_stderr"; then
    ACQUIRED_AGENTS+=("$slug")
    create_worktree "$slug" "$branch"
  else
    lock_rc=$?
    if [ "$lock_rc" -eq 1 ]; then
      echo "  SKIP: $slug locked by another session"
    else
      echo "  ERROR: failed to acquire $slug (exit $lock_rc):" >&2
      cat "$lock_stderr" >&2
      rm -f "$lock_stderr"
      exit 1  # fail-fast on real errors (gh auth, network, etc.)
    fi
  fi
  rm -f "$lock_stderr"
done

# ── Helper: check if agent was acquired ─────────────────────────────
is_acquired() {
  local needle="$1"
  # ${arr[@]+...} pattern: safe with set -u on bash < 4.4 (empty array)
  for a in ${ACQUIRED_AGENTS[@]+"${ACQUIRED_AGENTS[@]}"}; do
    [ "$a" = "$needle" ] && return 0
  done
  return 1
}

# ── 5. Configure git identity per worktree ─────────────────────────
# --worktree writes to .git/worktrees/<name>/config.worktree (isolated).
# --local would write to the shared .git/config (last-write-wins bug).
echo "[5/8] Configuring git identity..."
git -C "$REPO" config extensions.worktreeConfig true 2>/dev/null || true
for entry in "${AGENTS[@]}"; do
  IFS='|' read -r slug _gid _type _branch name email <<< "$entry"
  is_acquired "$slug" || continue  # skip agents we didn't acquire
  local_wt="/home/user/wetheagents-${slug}"
  [ -d "$local_wt" ] || continue
  git -C "$local_wt" config --worktree user.name "$name"
  git -C "$local_wt" config --worktree user.email "$email"
done

# ── 6. Deploy genomes ─────────────────────────────────────────────
echo "[6/8] Deploying genomes..."
for entry in "${AGENTS[@]}"; do
  IFS='|' read -r slug genome_id agent_type _branch _name _email <<< "$entry"
  is_acquired "$slug" || continue  # skip agents we didn't acquire
  deploy_genome "$slug" "$genome_id" "$agent_type"
done

# ── 6b. Deploy shared skills (gunnery) ────────────────────────────
echo "[6b/8] Deploying shared skills..."
SKILLS_SRC="$REPO/gunnery/skills"
if [ -d "$SKILLS_SRC" ]; then
  for entry in "${AGENTS[@]}"; do
    IFS='|' read -r slug _genome_id _agent_type _branch _name _email <<< "$entry"
    is_acquired "$slug" || continue
    wt="$REPO-${slug}"
    mkdir -p "${wt}/gunnery"
    cp -r "$SKILLS_SRC" "${wt}/gunnery/skills"
    echo "  ${slug}: gunnery/skills/ deployed"
  done
else
  echo "  SKIP: $SKILLS_SRC not found"
fi

# ── 7. Configure push remotes ─────────────────────────────────────
# NOTE: git remotes are stored in .git/config which is SHARED across all worktrees.
# Embedding per-agent tokens in the URL would cause the last-written token to win.
# Instead: use a credential helper that reads GITHUB_TOKEN from the environment.
# Each agent is launched with its own GITHUB_TOKEN set, so the right token is used.
echo "[7/8] Configuring push remotes..."

# Install credential helper (reads GITHUB_TOKEN from env at push time)
cat > /usr/local/bin/git-credential-github-token << 'CREDEOF'
#!/bin/bash
echo "username=x-access-token"
echo "password=${GITHUB_TOKEN}"
CREDEOF
chmod +x /usr/local/bin/git-credential-github-token

# Configure credential helper for github.com in the main repo (shared, that's fine)
git -C "$REPO" config credential.https://github.com.helper github-token

# Add a single push-origin remote (no embedded token — uses credential helper)
git -C "$REPO" remote remove push-origin 2>/dev/null || true
git -C "$REPO" remote add push-origin "https://github.com/WeTheAgents/wetheagents.git"
echo "  ok: push-origin configured (credential helper reads GITHUB_TOKEN from env)"

# ── 8. Start multi-provider auth proxy ────────────────────────────────
# Routes API requests by path prefix (/anthropic, /openai, /gemini) to upstream,
# transforms auth headers, and streams SSE responses.
AUTH_PROXY_SCRIPT="$REPO/scripts/auth_proxy.py"
AUTH_PROXY_PORT=18080
AUTH_PROXY_PIDFILE="/tmp/auth-proxy.pid"
AUTH_PROXY_STDOUT="/tmp/auth-proxy.stdout"

if [ -f "$AUTH_PROXY_SCRIPT" ]; then
  # Kill any existing proxy
  if [ -f "$AUTH_PROXY_PIDFILE" ]; then
    kill "$(cat "$AUTH_PROXY_PIDFILE")" 2>/dev/null || true
    rm -f "$AUTH_PROXY_PIDFILE"
  fi
  rm -f "$AUTH_PROXY_STDOUT"

  python3 "$AUTH_PROXY_SCRIPT" "$AUTH_PROXY_PORT" > "$AUTH_PROXY_STDOUT" 2>&1 &
  echo $! > "$AUTH_PROXY_PIDFILE"

  WEA_AUTH_PROXY_TOKEN=""
  for _ in {1..20}; do
    WEA_AUTH_PROXY_TOKEN="$(sed -n 's/^WEA_AUTH_PROXY_TOKEN=//p' "$AUTH_PROXY_STDOUT" 2>/dev/null | head -n 1)"
    [ -n "$WEA_AUTH_PROXY_TOKEN" ] && break
    kill -0 "$(cat "$AUTH_PROXY_PIDFILE")" 2>/dev/null || break
    sleep 0.1
  done
  export WEA_AUTH_PROXY_TOKEN

  cat "$AUTH_PROXY_STDOUT" 2>/dev/null || true
  rm -f "$AUTH_PROXY_STDOUT"
  if [ -z "$WEA_AUTH_PROXY_TOKEN" ]; then
    echo "[8/8] WARN: Auth proxy token was not captured"
  fi

  # Health check via /health endpoint
  HEALTH="000"
  for _ in {1..10}; do
    HEALTH=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $WEA_AUTH_PROXY_TOKEN" "http://127.0.0.1:$AUTH_PROXY_PORT/health" 2>/dev/null || echo "000")
    [ "$HEALTH" = "200" ] && break
    sleep 0.1
  done
  if [ "$HEALTH" = "200" ]; then
    PROVIDERS=$(curl -s -H "Authorization: Bearer $WEA_AUTH_PROXY_TOKEN" "http://127.0.0.1:$AUTH_PROXY_PORT/health" | python3 -c "import sys,json; print(', '.join(json.load(sys.stdin)['providers']))" 2>/dev/null || echo "?")
    echo "[8/8] Auth proxy started on port $AUTH_PROXY_PORT (PID $(cat "$AUTH_PROXY_PIDFILE"), providers: $PROVIDERS)"
  elif kill -0 "$(cat "$AUTH_PROXY_PIDFILE")" 2>/dev/null; then
    echo "[8/8] Auth proxy started on port $AUTH_PROXY_PORT (PID $(cat "$AUTH_PROXY_PIDFILE")) — health check failed"
  else
    echo "[8/8] WARN: Auth proxy failed to start"
  fi
else
  echo "[8/8] SKIP: auth_proxy.py not found at $AUTH_PROXY_SCRIPT"
fi

# ── Optional: Install codex CLI ────────────────────────────────────
if ! command -v codex &>/dev/null; then
  npm install -g @openai/codex 2>/dev/null && echo "codex CLI installed" \
    || echo "codex CLI install failed (non-fatal)"
fi

# ── Summary ────────────────────────────────────────────────────────
SESSION_TOKEN_FILE="/home/claude/.claude/remote/.session_ingress_token"

echo ""
echo "=== Setup Complete (session: $SESSION_ID) ==="
if [ ${#ACQUIRED_AGENTS[@]} -gt 0 ]; then
  echo "Acquired agents: ${ACQUIRED_AGENTS[*]}"
else
  echo "Acquired agents: none"
fi
echo ""
echo "Worktrees:"
git worktree list
echo ""
echo "Auth proxy: http://127.0.0.1:$AUTH_PROXY_PORT"
echo "  /anthropic/v1/...  → api.anthropic.com"
echo "  /openai/v1/...     → api.openai.com"
echo "  /gemini/v1beta/... → generativelanguage.googleapis.com"
echo "  /health            → status + provider list"
echo ""
echo "Agent launch (from Agent0 session):"
echo "  Claude-1:"
echo "    cd /home/user/wetheagents-claude-1"
echo "    source $REPO/.venv/bin/activate"
echo "    GITHUB_TOKEN=\$CLAUDE1_GITHUB_TOKEN WEA_AGENT=Claude-1@claude \\"
echo "      WEA_AUTH_PROXY_TOKEN=\"$WEA_AUTH_PROXY_TOKEN\" \\"
echo "      env -u CLAUDECODE -u CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR -u CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR \\"
echo "      ANTHROPIC_API_KEY=\"\$(cat $SESSION_TOKEN_FILE)\" \\"
echo "      ANTHROPIC_BASE_URL=\"http://127.0.0.1:$AUTH_PROXY_PORT/anthropic\" \\"
echo "      claude -p --model haiku --permission-mode default '...'"
echo ""
echo "  Codex-2:"
echo "    WEA_AUTH_PROXY_TOKEN=\"$WEA_AUTH_PROXY_TOKEN\" \\"
echo "    OPENAI_BASE_URL=\"http://127.0.0.1:$AUTH_PROXY_PORT/openai\" \\"
echo "      GITHUB_TOKEN=\$CODEX2_GITHUB_TOKEN WEA_AGENT=Codex-2@codex codex '...'"
echo ""
echo "  Cursor-3:      (IDE — reads AGENTS.md in worktree)"
echo "  gemini-4:      (CLI — reads AGENTS.local.md in worktree)"
echo ""
echo "Genome retrieve:"
echo "  bash scripts/cloud_agent_setup.sh --retrieve"
echo "  bash scripts/cloud_agent_setup.sh --retrieve --agent cursor-3"
