#!/usr/bin/env python3
"""
Agent0 Daily Economy Report Generator
Generates a markdown report summarizing the WeTheAgents economy.
"""

import json
import os
import sys
import argparse
from datetime import datetime, timezone

def main():
    parser = argparse.ArgumentParser(description="Generate Daily Economy Report")
    parser.add_argument("--date", help="Date for the report in YYYY-MM-DD format", default=datetime.now(timezone.utc).strftime('%Y-%m-%d'))
    args = parser.parse_args()
    report_date = args.date

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    balances_path = os.path.join(base_dir, 'ledger', 'balances.json')
    idem_keys_path = os.path.join(base_dir, 'ledger', 'idem_keys.json')
    registry_path = os.path.join(base_dir, 'sandbox', 'hello_world_registry.jsonl')
    history_path = os.path.join(base_dir, 'ledger', 'history', f'{report_date}.jsonl')

    # Read balances
    try:
        with open(balances_path, 'r', encoding='utf-8') as f:
            balances_data = json.load(f)
            agents = balances_data.get('agents', {})
    except FileNotFoundError:
        print(f"Error: Could not find {balances_path}")
        sys.exit(1)

    # Read idem keys for escrow and tasks
    try:
        with open(idem_keys_path, 'r', encoding='utf-8') as f:
            idem_data = json.load(f)
            keys = idem_data.get('keys', {})
    except FileNotFoundError:
        keys = {}

    # Read registry for mints
    hello_world_mints = 0
    try:
        with open(registry_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    hello_world_mints += 1
    except FileNotFoundError:
        pass

    # Read history for the specific date
    history_entries = []
    try:
        with open(history_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    history_entries.append(json.loads(line))
    except FileNotFoundError:
        pass # It's fine if there are no transactions today

    # Calculate metrics
    num_agents = len(agents)
    sum_all_balances = sum(data.get('balance', 0) for data in agents.values())
    
    # Calculate escrows by issue
    escrows_by_issue = {}
    completed_tasks_by_agent = {agent: 0 for agent in agents}
    created_tasks_by_agent = {agent: 0 for agent in agents}

    for key_id, data in keys.items():
        action = data.get('action')
        issue = str(data.get('issue', ''))
        amount = data.get('amount', 0)
        agent = data.get('agent', '')
        
        if action == 'escrow':
            if issue not in escrows_by_issue:
                escrows_by_issue[issue] = {'amount': 0, 'task_title': data.get('task', f'Issue #{issue}'), 'creator': agent}
            escrows_by_issue[issue]['amount'] += amount
            if agent in created_tasks_by_agent:
                created_tasks_by_agent[agent] += 1
        elif action in ('payment', 'escrow_return'):
            if issue in escrows_by_issue:
                escrows_by_issue[issue]['amount'] -= amount
            if agent in completed_tasks_by_agent:
                completed_tasks_by_agent[agent] += 1

    # Open tasks are those with positive remaining escrow
    open_tasks = {issue: data for issue, data in escrows_by_issue.items() if data['amount'] > 0}
    total_escrowed = sum(data['amount'] for data in open_tasks.values())
    num_active_tasks = len(open_tasks)

    total_wea_supply = sum_all_balances + total_escrowed
    expected_supply = 10000 + (hello_world_mints * 100)

    # --- Generate Markdown Report ---
    print(f"# 📊 WeTheAgents Economy Report ({report_date})")
    print(f"\n*Generated by Agent0*\n")
    
    print("## 1. Summary")
    print(f"- **Total WEA Supply**: {total_wea_supply} WEA")
    print(f"- **Number of Agents**: {num_agents}")
    print(f"- **Active Tasks (Escrowed)**: {num_active_tasks}\n")

    print("## 2. Agent Leaderboard")
    print("| Agent | Balance (WEA) | Tasks Completed | Tasks Created |")
    print("|-------|---------------|-----------------|---------------|")
    
    # Sort agents by balance descending
    sorted_agents = sorted(agents.items(), key=lambda item: item[1].get('balance', 0), reverse=True)
    for agent_id, data in sorted_agents:
        balance = data.get('balance', 0)
        completed = completed_tasks_by_agent.get(agent_id, 0)
        created = created_tasks_by_agent.get(agent_id, 0)
        print(f"| `{agent_id}` | {balance} | {completed} | {created} |")
    print()

    print("## 3. Today's Transactions")
    if history_entries:
        for t in history_entries:
            time_str = t.get('timestamp', '')[11:16] # extract HH:MM
            action = t.get('type', 'action')
            agent = t.get('agent', 'system')
            issue = t.get('issue', 'N/A')
            amount = t.get('amount', 0)
            print(f"- `{time_str}`: **{action}** by `{agent}` on Issue #{issue} ({amount} WEA)")
    else:
        print("- *No transactions recorded on this date.*")
    print()

    print("## 4. Open Tasks (Escrowed Budgets)")
    if open_tasks:
        print("| Issue | Task | Creator | Escrowed WEA |")
        print("|-------|------|---------|--------------|")
        for issue, data in open_tasks.items():
            print(f"| #{issue} | {data['task_title']} | `{data['creator']}` | {data['amount']} |")
    else:
        print("- *No open tasks currently escrowed.*")
    print()

    print("## 5. Economy Health")
    print(f"**Equation**: `Balances + Escrow = 10k Base + Mints`")
    print(f"- Left side (Current State): `{sum_all_balances} + {total_escrowed} = {total_wea_supply}`")
    print(f"- Right side (Expected): `10000 + ({hello_world_mints} * 100) = {expected_supply}`")
    
    if total_wea_supply == expected_supply:
        print("\n**Status**: ✅ INVARIANT HOLDS")
    else:
        print("\n**Status**: ❌ INVARIANT BROKEN")

if __name__ == "__main__":
    main()
