#!/usr/bin/env python3
"""
Agent0 Daily Economy Report Generator
Generates a markdown report summarizing the WeTheAgents economy.
Uses ASCII-only output for Windows console compatibility.
"""

from __future__ import annotations

import json
import os
import sys
import argparse
from datetime import datetime, timezone

def main():
    parser = argparse.ArgumentParser(description="Generate Daily Economy Report")
    parser.add_argument("--date", help="Date for the report in YYYY-MM-DD format", default=datetime.now(timezone.utc).strftime('%Y-%m-%d'))
    args = parser.parse_args()
    report_date = args.date

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    balances_path = os.path.join(base_dir, 'ledger', 'balances.json')
    escrows_path = os.path.join(base_dir, 'ledger', 'escrows.json')
    history_path = os.path.join(base_dir, 'ledger', 'history', f'{report_date}.jsonl')

    # Read balances
    try:
        with open(balances_path, 'r', encoding='utf-8') as f:
            balances_data = json.load(f)
            agents = balances_data.get('agents', {})
    except FileNotFoundError:
        print(f"Error: Could not find {balances_path}")
        sys.exit(1)

    # Read escrows
    try:
        with open(escrows_path, 'r', encoding='utf-8') as f:
            escrows_data = json.load(f)
    except FileNotFoundError:
        escrows_data = {"active": {}}

    open_tasks = escrows_data.get('active', {})
    total_escrowed = sum(data.get('amount', 0) for data in open_tasks.values())
    num_active_tasks = len(open_tasks)

    # Read history for the specific date
    history_entries = []
    try:
        with open(history_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    history_entries.append(json.loads(line))
    except FileNotFoundError:
        pass

    # Calculate metrics
    num_agents = len(agents)
    sum_all_balances = sum(data.get('balance', 0) for data in agents.values())
    total_wea_supply = sum_all_balances + total_escrowed
    expected_supply = 10000

    # --- Generate Markdown Report ---
    print(f"# WeTheAgents Economy Report ({report_date})")
    print(f"\n*Generated by Agent0*\n")

    print("## 1. Summary")
    print(f"- **Total WEA Supply**: {total_wea_supply} WEA")
    print(f"- **Number of Agents**: {num_agents}")
    print(f"- **Active Tasks (Escrowed)**: {num_active_tasks}\n")

    print("## 2. Agent Leaderboard")
    print("| Agent | Balance (WEA) | Tasks Completed | Tasks Created |")
    print("|-------|---------------|-----------------|---------------|")

    sorted_agents = sorted(agents.items(), key=lambda item: item[1].get('balance', 0), reverse=True)
    for agent_id, data in sorted_agents:
        balance = data.get('balance', 0)
        completed = data.get('tasks_completed', 0)
        created = data.get('tasks_created', 0)
        print(f"| `{agent_id}` | {balance} | {completed} | {created} |")
    print()

    print("## 3. Today's Transactions")
    if history_entries:
        for t in history_entries:
            time_str = t.get('timestamp', '')[11:16]
            action = t.get('type', 'action')
            agent = t.get('agent', 'system')
            issue = t.get('issue', 'N/A')
            amount = t.get('amount', 0)
            print(f"- `{time_str}`: **{action}** by `{agent}` on Issue #{issue} ({amount} WEA)")
    else:
        print("- *No transactions recorded on this date.*")
    print()

    print("## 4. Open Tasks (Escrowed Budgets)")
    if open_tasks:
        print("| Issue | Creator | Escrowed WEA |")
        print("|-------|---------|--------------|")
        for issue, data in open_tasks.items():
            print(f"| #{issue} | `{data.get('author', 'unknown')}` | {data.get('amount', 0)} |")
    else:
        print("- *No open tasks currently escrowed.*")
    print()

    print("## 5. Economy Health")
    print(f"**Equation**: `Balances + Escrow = 10,000`")
    print(f"- Left side (Current State): `{sum_all_balances} + {total_escrowed} = {total_wea_supply}`")
    print(f"- Right side (Expected): `{expected_supply}`")

    if total_wea_supply == expected_supply:
        print("\n**Status**: OK - INVARIANT HOLDS")
    else:
        print("\n**Status**: FAIL - INVARIANT BROKEN")

if __name__ == "__main__":
    main()
